name: innovation_hub
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  adaptive_dialog: ^1.8.2
  easy_stepper: ^0.3.2
  fl_chart: ^0.61.0
  flex_color_scheme: ^7.0.0-dev.2
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.0
  flutter_hooks: ^0.18.6
  flutter_riverpod: ^2.3.1
  font_awesome_flutter: ^10.4.0
  go_router: ^6.2.0
  hooks_riverpod: ^2.3.2
  intl: ^0.18.0
  lottie: ^2.2.0
  riverpod_annotation: ^2.0.1
  textfield_tags: ^2.0.2
  url_strategy: ^0.2.0
  window_manager: ^0.3.1

dev_dependencies:
  build_runner: ^2.3.3
  # riverpod_lint depent on this, custom_lint
  custom_lint: ^0.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  # code generator for riverpod
  riverpod_generator: ^2.1.3
  # riverpod lint help to warn or highlight riverpod syntax
  riverpod_lint: ^1.1.5
  test: ^1.22.0

flutter:
  uses-material-design: true

  assets:
    - assets/brand/
    - assets/images/
    - assets/images/sit-icons/
    - assets/animations/
